name: Fetch JSON Secrets

on:
  workflow_call:
    inputs:
      json_url:
        required: true
        type: string

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  download-json:
    runs-on: ubuntu-latest
    steps:
      - name: Download JSON with Retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 1
          max_attempts: 3
          shell: python
          command: |
            import requests
            import time

            url = "${{ inputs.json_url }}"
            
            for attempt in range(5):
                try:
                    print(f"Downloading (Attempt {attempt + 1})...")
                    r = requests.get(url, timeout=20)
                    r.raise_for_status()
                    with open('secrets.json', 'wb') as f:
                        f.write(r.content)
                    break
                except Exception as e:
                    if attempt < 4:
                        time.sleep(5 * (2 ** attempt))
                    else: raise e

      - name: Upload JSON Artifact
        uses: actions/upload-artifact@v4
        with:
          name: json-secrets
          path: secrets.json
          retention-days: 1
